spring:
  profiles:
    active: local
  config:
    import: classpath:matching.yml

# 이 application.yml을 사용하려면 Edit Configuration > active profiles 를 local 혹은 dev 등으로 설정해야 된다.
# (default local 설정을 못찾았습니다)
---
spring:
  profiles:
    include:
      - matching
    group:
      dev: dev
      prod: prod
      local: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://112.220.19.35:15432/matching
    username: matching
    password: Matching153!%#
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      show-sql: true
server:
  port:
    8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://112.220.19.35:15432/matching
    username: matching
    password: Matching153!%#
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      show-sql: true
server:
  port:
    8080

---
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://112.220.19.35:15432/matching
    username: matching
    password: Matching153!%#
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      show-sql: true
server:
  port:
    8080
